const array = [1, 2, 3, 4, 5];

const b = [...array]; //In this example, we are using the spread operator (...) to create a new array 'b' that contains all the elements of the original 'array'. The spread operator allows us to expand the elements of the 'array' into individual values, which are then used to construct the new array 'b'. The value of 'b' will be [1, 2, 3, 4, 5]. It is important to note that using the spread operator creates a shallow copy of the original array, meaning that if the original array contains objects or nested arrays, the references to those objects will be copied rather than the objects themselves. However, in this case, since the original array contains only primitive values (numbers), the new array 'b' will contain independent copies of those values.
console.log(b); //Output: [1, 2, 3, 4, 5]

const c = [...array, 6, 7]; //In this example, we are using the spread operator (...) to create a new array 'c' that contains all the elements of the original 'array' followed by the additional values 6 and 7. The spread operator allows us to expand the elements of the 'array' into individual values, which are then used to construct the new array 'c'. The value of 'c' will be [1, 2, 3, 4, 5, 6, 7]. Similar to the previous example, using the spread operator creates a shallow copy of the original array, so if the original array contains objects or nested arrays, the references to those objects will be copied rather than the objects themselves. However, since the original array contains only primitive values (numbers), the new array 'c' will contain independent copies of those values along with the additional values 6 and 7.
console.log(c); //Output: [1, 2, 3, 4, 5, 6, 7]

const d = [0, ...array, 6]; //In this example, we are using the spread operator (...) to create a new array 'd' that contains the value 0 followed by all the elements of the original 'array' and then the additional value 6. The spread operator allows us to expand the elements of the 'array' into individual values, which are then used to construct the new array 'd'. The value of 'd' will be [0, 1, 2, 3, 4, 5, 6]. Similar to the previous examples, using the spread operator creates a shallow copy of the original array, so if the original array contains objects or nested arrays, the references to those objects will be copied rather than the objects themselves. However, since the original array contains only primitive values (numbers), the new array 'd' will contain independent copies of those values along with the additional values 0 and 6.
console.log(d); //Output: [0, 1, 2, 3, 4, 5, 6]

